config/routes.rb
Rails.application.routes.draw do
    get 'welcome/index'
    get 'goodbye', to: 'goodbye#goodbye'

    resources :customers do
      resources :orders
    end

    root 'welcome#index'
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  has_many :orders, dependent: :destroy
  validates :name, presence: true,
            length: { minimum: 4 }
  validates :email, presence: true
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :show]

  def index
    @customer = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def new
    @customer = Customer.new
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def create
    @customer = Customer.new(customer_params)

    if @customer.save
      redirect_to @customer
    else
      render 'new'
    end
  end

  def update
    @customer = Customer.find(params[:id])

    if @customer.update(customer_params)
      redirect_to @customer
    else
      render 'edit'
    end
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy

    redirect_to customers_path
  end

  private
    def customer_params
      params.require(:customer).permit(:name, :email)
    end
end

app/controllers/goodbye_controller.rb
class GoodbyeController < ApplicationController
  def goodbye
      @bye = "Goodbye! / ¡Adios! / 안녕히!"
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  http_basic_authenticate_with name: "admin", password: "admin", except: [:index, :show]

  def create
    @customer = Customer.find(params[:customer_id])
    @order = @customer.orders.create(order_params)
    redirect_to customer_path(@customer)
  end

  def destroy
    @customer = Customer.find(params[:customer_id])
    @order = @customer.orders.find(params[:id])
    @order.destroy
    redirect_to customer_path(@customer)
  end

  private
    def order_params
      params.require(:order).permit(:order, :description)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def index
        @hello =  "Hello World / ¡Hola Mundo! / 안녕 세상!"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/goodbye_helper.rb
module GoodbyeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/customers/_form.html.erb
<%= form_with model: @customer, local: true do |form| %>
  <% if @customer.errors.any? %>
    <div id = "error_explanation">
      <h3>
        <%= pluralize(@customer.errors.count, "error") %>
        prohibited this Customer from being saved:
      </h3>
      <ul>
        <% @customer.errors.full_messages.each do |msg| %>
          <li> <%= msg %> </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/customers/edit.html.erb
<h3> Edit Customer </h3>

<%= render 'form' %>

<%= link_to 'Back', customer_path %>

app/views/customers/index.html.erb
<h3> Listing Customers </h3>

<table>
  <tr>
    <th> Name </th>
    <th> Email </th>
    <th colspan= "3"></th>
  </tr>

  <% @customer.each do |customer| %>
    <tr>
      <td> <%= customer.name %> </td>
      <td> <%= customer.email %> </td>
      <td> <%= link_to 'Show', customer_path(customer) %> </td>
      <td> <%= link_to 'Edit', edit_customer_path(customer) %> </td>
      <td> <%= link_to 'Destroy', customer_path(customer), method: :delete, data: { confirm: 'Are you sure?' } %> </td>
    </tr>
  <% end %>
</table>
<br>
<%= link_to 'New Customer', new_customer_path %>



app/views/customers/new.html.erb
<h3> New Customer </h3>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p>
  <strong> Name: </strong>
  <%= @customer.name %>
</p>

<p>
  <strong> Email: </strong>
  <%= @customer.email %>
</p>

<h4> Orders </h4>
<%= render @customer.orders %>

<h4> Add an Order: </h4>
<%= render 'orders/form' %>

<%= link_to 'Edit', edit_customer_path(@customer) %>
<%= link_to 'Back', customers_path %>

app/views/goodbye/goodbye.html.erb
<h1> <%= @bye %> </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HelloWorld</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_with(model: [@customer, @customer.orders.build], local: true) do |form| %>
  <p>
    <%= form.label :order %><br>
    <%= form.text_field :order %>
  </p>

  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/orders/_order.html.erb
<p>
  <strong> Order: </strong>
  <%= order.order %>
</p>

<p>
  <strong> Description: </strong>
  <%= order.description %>
</p>

<p>
  <%= link_to 'Destroy Order', [order.customer, order], method: :delete, data: { confirm: 'Are you sure?'} %>
</p>

app/views/welcome/index.html.erb
<h2> Uebung2</h2>
<h3> <%= @hello %> </h3>
<br></br>

<h2> Uebung3 </h2>
<%= link_to 'Show Customers', controller: 'customers' %>
<br>
<%= link_to 'New Customer', new_customer_path %>